### ISSUE TITLE
TypeError purchaseAPhoneNumber is not a function

### ISSUE THREAD

**Issue by parkthecar16** [flowroute/flowroute-sdk-v3-nodejs#15]
Strange error I am running into. I am using the v3 library with Numbers v2 and NumbersController and I am successfully using several other functions such as searchForPurchasablePhoneNumbers. However, when I use the purchaseAPhoneNumber function I get a type error as you see below:
`TypeError: numbersController.purchaseAPhoneNumber is not a function
    at C:\Users\Admin\source\repos\flowroute-sdk-v3-nodejs\index.js:223:37
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`
Any info regarding this would be greatly appreciated.

**Comment by parkthecar16** [comment]
I solved this problem by looking in the `NumbersController` file where the functions are created. The problem is `purchaseAPhoneNumber` is wrong so you guys should change the guides and documentation, after looking in the `NumbersController` file the correct function is `createPurchaseAPhoneNumber`. If anyone runs into this problem make sure to look in the corresponding controller file and use the same name as where the method is created.
